PhotoDon/urls.py
# from django.conf.urls import include

from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from PhotoDon.settings import STATIC_URL
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
sitemaps={
    'static':StaticViewSitemap,
    'blog':BlogSitemap
}
handler404 = 'website.views.view_404'


urlpatterns = [
    path('admin/', admin.site.urls), 
    path ('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path ('accounts/', include('accounts.urls')),
    path ('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    ]
    
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name='blog'

urlpatterns = [

    path ('',blog_view,name='index'),
    path ('<int:pid>',blog_post,name='single'),
    path ('author/<str:author_username>',blog_view,name='author'),
    path ('category/<str:cat_name>',blog_view,name='category'),
    path ('tag/<str:tag_name>',blog_view,name='tag'),
    path ('test/',test,name='test'),
    path ('search/',blog_search,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

templates/base.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Perfect</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin"/>
    <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap" media="print" onload="this.media='all'"/>
    <noscript>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap"/>
    </noscript>
    <link href="{% static 'css/bootstrap.min.css?ver=1.2.0' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/all.min.css?ver=1.2.0' %}" rel="stylesheet">
    <link href="{% static 'css/main.css?ver=1.2.0' %}" rel="stylesheet">
  </head>

{% block content %}

{% endblock %}

  <footer class="pp-footer">
    <div class="container py-5">
      <div class="row text-center">
        <div class="col-md-12"><a class="pp-facebook btn btn-link" href="#"><i class="fab fa-facebook-f fa-2x " aria-hidden="true"></i></a><a class="pp-twitter btn btn-link " href="#"><i class="fab fa-twitter fa-2x " aria-hidden="true"></i></a><a class="pp-youtube btn btn-link" href="#"><i class="fab fa-youtube fa-2x" aria-hidden="true"></i></a><a class="pp-instagram btn btn-link" href="#"><i class="fab fa-instagram fa-2x " aria-hidden="true"></i></a></div>
        <div class="col-md-12">
          <p class="mt-3">Copyright &copy; Photo Perfect. All rights reserved.<br>Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
        </div>
      </div>
    </div>
  </footer>
  <script src="{% static 'scripts/jquery.min.js?ver=1.2.0' %}"></script>
  <script src="{% static 'scripts/bootstrap.bundle.min.js?ver=1.2.0' %}"></script>
  <script src="{% static 'scripts/main.js?ver=1.2.0' %}"></script>
</body>
</html>

templates/popularposts.html
<ul>

    {%  for post in posts   %}
    {% if post.id.has_next %}
    {% url 'blog:single' pid=post.id %}"
    {% endif %}
    {%  endfor  %}

</ul>